version: '3.4'

services: 
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: nat