version: '3.4'

services:
  mysqldb:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: localpassword_1
    ports:
        - 3306:3306

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: nat